# Generated by Django 6.0.1 on 2026-02-04 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0004_product_is_infinite_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
