# Generated by Django 6.0.1 on 2026-02-04 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0005_shop_latitude_shop_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='is_physical',
            field=models.BooleanField(default=True),
        ),
    ]
