# Generated by Django 6.0.1 on 2026-02-05 19:42

import api.validators
import shops.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0007_alter_product_image_alter_shop_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=shops.models.product_image_path, validators=[api.validators.validate_file_size, api.validators.validate_image_extension]),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='shop',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=shops.models.shop_image_path, validators=[api.validators.validate_file_size, api.validators.validate_image_extension]),
        ),
        migrations.AlterField(
            model_name='shop',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='shop',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active')], db_index=True, default='active', max_length=10),
        ),
    ]
